### PR TITLE
Registration and login APIs

### PR DESCRIPTION
**Pull request by keyurkadam**
Added registration and login APIs

### CODE REVIEW

**Comment by omoniyi24** [comment]
Could you please include unit test?

**Comment by keyurkadam** [comment]
#6 and #7 issued have been done by my side and also added the unit test class.

**Comment by omoniyi24** [comment]
Great work, @keyurkadam , the PR is looking much better! To further enhance our code coverage, perhaps we could consider testing additional scenarios, such as when login or registration fails. This might give us a more comprehensive insight into our application's robustness. What do you think?

**Comment by keyurkadam** [comment]
@omoniyi24 Sure, it is done!

I've added tests to cover scenarios where login or registration fails. These tests aim to provide a more comprehensive insight into our application's robustness by ensuring that it handles error cases appropriately. Let me know if you have any further questions or if there's anything else you'd like to add or modify.

**Review by DeTuksa — APPROVED** [review]

**Comment by omoniyi24** [comment]
Weldone @keyurkadam. @parthgohel1729 I think it's safe to merge now, what do you think?

**Pull request merged**
